# Generated by Django 3.0.6 on 2020-06-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='художник')),
                ('years_of_life', models.PositiveSmallIntegerField()),
                ('about_painter', models.TextField(verbose_name='немного о художнике')),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('RS', 'roman style'), ('GS', 'gothic style'), ('BQ', 'baroque'), ('CM', 'classicism'), ('SM', 'sentimentalism'), ('RM', 'romanticism'), ('RE', 'realism'), ('MO', 'modernism'), ('SY', 'symbolism'), ('IM', 'impressionism'), ('SU', 'surrealism'), ('CU', 'cubism'), ('FU', 'futurism'), ('AB', 'abstractionism'), ('PM', 'postmodernism')], max_length=40)),
                ('trend_descrition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название картины')),
                ('writing_time', models.PositiveSmallIntegerField()),
                ('descrition', models.TextField()),
                ('image', models.ImageField(upload_to='pictures_images/')),
                ('mood', models.CharField(choices=[('PO', 'positive'), ('NE', 'negative'), ('MI', 'middle'), ('FR', 'frightening'), ('MX', 'mixed')], max_length=25)),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Painter')),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Trend')),
            ],
        ),
        migrations.CreateModel(
            name='Example_Trend_Posters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='example_trend_posters/')),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures.Trend')),
            ],
        ),
    ]
