# Generated by Django 3.0.6 on 2020-06-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20200612_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painter',
            name='years_of_life',
        ),
        migrations.AddField(
            model_name='painter',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='painter',
            name='date_of_death',
            field=models.DateField(null=True),
        ),
    ]
