# Generated by Django 3.0.6 on 2020-06-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20200612_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='about_painter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='painter',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
